#:schema node_modules/@cloudflare/workers-types/worker-configuration.d.ts
name = "ocpp-chaos-simulator"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2025-08-15"

# Build configuration
[build]
command = "npx @cloudflare/next-on-pages"

# Enable logging and observability
[observability]
enabled = true


# Worker configuration
compatibility_flags = ["nodejs_compat", "streams_enable_constructors"]

# Environment variables
[env.production.vars]
NODE_ENV = "production"

# Custom domain configuration
[[env.production.routes]]
pattern = "ocpp.sankalpnarula.com/*"
zone_name = "sankalpnarula.com"

# KV namespaces (if needed for caching)
# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
