# Default configuration for OCPP Chaos Simulator

server:
  host: "localhost"
  port: 8080

database:
  type: "sqlite"
  path: "./data/simulator.db"

ocpp:
  default_version: "1.6"
  timeout: 30
  # default_endpoint: "ws://localhost:8080/ocpp"
  # default_auth_user: ""  # Optional: Default username for basic auth
  # default_auth_pass: ""  # Optional: Default password for basic auth

logging:
  level: "info"
  format: "json"
